name: sdvgo
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  animate_gradient: ^0.0.3
  google_fonts: ^6.2.1
  camera: ^0.10.5
  google_sign_in: ^6.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  yx_scope_flutter: ^1.0.0
  yx_scope: 1.0.2
  flutter_bloc: 9.1.0
  bloc: ^9.0.0

  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.5.3
  yx_scope_linter: ^0.1.2

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  generate: true # Добавить эту строку
  assets:
    - assets/fonts/ComicSansMS.ttf
    - assets/fonts/Chococooky.ttf
    - assets/images/smiley_face.png
  fonts:
    - family: ComicSansMS
      fonts:
        - asset: assets/fonts/ComicSansMS.ttf
    - family: ChocoCooky
      fonts:
        - asset: assets/fonts/Chococooky.ttf

  uses-material-design: true
