name: sdvgo
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  animate_gradient: ^0.0.3
  google_fonts: ^6.2.1
  camera: ^0.10.5
  google_sign_in: ^6.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flame: ^1.26.1

  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  generate: true # Добавить эту строку
  assets:
    - assets/fonts/ComicSansMS.ttf
    - assets/fonts/Chococooky.ttf
    - assets/images/
  fonts:
    - family: ComicSansMS
      fonts:
        - asset: assets/fonts/ComicSansMS.ttf
    - family: ChocoCooky
      fonts:
        - asset: assets/fonts/Chococooky.ttf

  uses-material-design: true
